Repository AY1920S1-CS2103T-T09-4/main, pull requests merged in 2019-11, with the labels that each got.

#194 Fix OrderBook cannot be read after saving bug
  src/main/java/seedu/address/MainApp.java
Labels: type.Bug

#223 Fix OrderBook cannot complete order bug
  src/main/java/seedu/address/logic/commands/CompleteOrderCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/phone/Phone.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CompleteOrderCommandTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: severity.High, type.Bug

#222 Fix bugs + make schedule commands undoable
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/addcommand/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/clearcommand/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/panels/CalendarPanel.java
  src/test/java/seedu/address/logic/commands/addcommand/AddScheduleCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: severity.High, type.Bug

#250 Fix bugs + make schedule commands undoable
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/addcommand/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/clearcommand/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/panels/CalendarPanel.java
  src/test/java/seedu/address/logic/commands/addcommand/AddScheduleCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug

#196 Fix Pe bugs
  docs/UserGuide.adoc
  src/main/java/seedu/address/statistic/DateUtil.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/java/seedu/address/ui/cards/ArchivedOrderCard.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/resources/view/ArchivedOrderListCard.fxml
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/PhoneListCard.fxml
  src/main/resources/view/SMLTheme.css
  src/main/resources/view/ScheduleListCard.fxml
  src/test/java/seedu/address/ui/OrderListPanelTest.java
Labels: type.Bug

#248 Fix pe bugs
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/nodes/phone/PhoneCapacityNode.java
  src/main/java/seedu/address/logic/nodes/schedule/ScheduleTimeNode.java
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/model/customer/CustomerTest.java
Labels: priority.High, type.Bug

#190 Updated DG for export feature
  docs/DeveloperGuide.adoc
Labels: type.Task

#252 Fix pe bugs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Bug

#251 added minor logging
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/LogsCenter.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, type.Task

#253 Filename bug fix
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: priority.High, severity.Medium, type.Bug

#256 Fix issue: Create data folder during init
  src/main/java/seedu/address/MainApp.java
Labels: priority.High, severity.High, type.Bug

#254 add to sample order util, add showing of Customer Tags
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/cards/ArchivedOrderCard.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/resources/view/ArchivedOrderListCard.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/SMLTheme.css
Labels: type.Bug

#255 Check for Customer and Phone tags in OrderContainsKeywordsPredicate
  src/main/java/seedu/address/logic/commands/addcommand/AddOrderCommand.java
  src/main/java/seedu/address/model/order/predicates/OrderContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: priority.Medium, type.Task

#265 Minor fixes
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/ui/panels/CalendarPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/SellerManagerParserTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/ScheduleUtil.java
Labels: type.Bug

#278 Update UG/DG and Fix Undo/Redo Bug
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UndoRedoStackObjectDiagram4.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/diagrams/UndoableCommandClassDiagram.puml
  docs/images/dg-diagram/UndoRedoStackObjectDiagram4.png
  docs/images/dg-diagram/UndoSequenceDiagram.png
  docs/images/dg-diagram/UndoableCommandClassDiagram.png
  src/main/java/seedu/address/logic/UndoRedoStack.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/UndoRedoStackTest.java
Labels: priority.High, type.Task

#280 Fix bug
  src/main/java/seedu/address/logic/GraphWithPreamble.java
  src/main/java/seedu/address/logic/GraphWithStartNode.java
  src/main/java/seedu/address/logic/GraphWithStartNodeAndPreamble.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/phone/Cost.java
  src/test/java/seedu/address/model/order/PriceTest.java
  src/test/java/seedu/address/model/phone/CostTest.java
Labels: type.Bug

#281 Format fixing for export
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: priority.High

#291 Add Storage book test
  src/test/data/JsonCustomerBookStorageTest/invalidAndValidCustomerCustomerBook.json
  src/test/data/JsonCustomerBookStorageTest/invalidCustomerCustomerBook.json
  src/test/data/JsonCustomerBookStorageTest/notJsonFormatCustomerBook.json
  src/test/data/JsonOrderBookStorageTest/invalidAndValidOrderOrderBook.json
  src/test/data/JsonOrderBookStorageTest/invalidOrderOrderBook.json
  src/test/data/JsonOrderBookStorageTest/notJsonFormatOrderBook.json
  src/test/data/JsonPhoneBookStorageTest/invalidAndValidPhonePhoneBook.json
  src/test/data/JsonPhoneBookStorageTest/invalidPhonePhoneBook.json
  src/test/data/JsonPhoneBookStorageTest/notJsonFormatPhoneBook.json
  src/test/data/JsonScheduleBookStorageTest/invalidAndValidScheduleScheduleBook.json
  src/test/data/JsonScheduleBookStorageTest/invalidScheduleScheduleBook.json
  src/test/data/JsonScheduleBookStorageTest/notJsonFormatScheduleBook.json
  src/test/java/seedu/address/storage/JsonCustomerBookStorageTest.java
  src/test/java/seedu/address/storage/JsonOrderBookStorageTest.java
  src/test/java/seedu/address/storage/JsonPhoneBookStorageTest.java
  src/test/java/seedu/address/storage/JsonScheduleBookStorageTest.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalPhones.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High

#287 Added PPP, Update UG/DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ExportSequenceDiagram.puml
  docs/images/ExportCommand.png
  docs/images/ExportSequenceDiagram.png
  docs/images/exportCSV.png
  docs/team/yeodonghan.adoc
Labels: priority.High
