Repository AY1920S1-CS2103T-T09-4/main, pull requests merged in 2019-10, with the labels that each got.

#75 Update Model Manager
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/CustomerBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/OrderBook.java
  src/main/java/seedu/address/model/PhoneBook.java
  src/main/java/seedu/address/model/ReadOnlyDataBook.java
  src/main/java/seedu/address/model/ScheduleBook.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/order/exceptions/DuplicateOrderException.java
  src/main/java/seedu/address/model/order/exceptions/OrderNotFoundException.java
  src/main/java/seedu/address/model/phone/UniquePhoneList.java
  src/main/java/seedu/address/model/phone/exceptions/DuplicatePhoneException.java
  src/main/java/seedu/address/model/phone/exceptions/PhoneNotFoundException.java
  src/main/java/seedu/address/model/schedule/UniqueScheduleList.java
  src/main/java/seedu/address/model/schedule/exceptions/DuplicateScheduleException.java
  src/main/java/seedu/address/model/schedule/exceptions/ScheduleNotFoundException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High

#76 Programmatically switch tab panels and Commands
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListPhoneCommand.java
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/commands/PanelType.java
  src/main/java/seedu/address/model/CustomerBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPanel.java
  src/main/java/seedu/address/ui/cards/CustomerCard.java
  src/main/java/seedu/address/ui/panels/CustomerListPanel.java
  src/main/java/seedu/address/ui/panels/PhoneListPanel.java
  src/main/resources/images/orderIcon.png
  src/main/resources/images/peopleIcon.png
  src/main/resources/images/phoneIcon.png
  src/main/resources/images/scheduleIcon.png
  src/main/resources/view/CustomerListPanel.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderListPanel.fxml
  src/main/resources/view/PhoneListPanel.fxml
  src/main/resources/view/ScheduleListPanel.fxml
  src/main/resources/view/TabPanel.fxml
Labels: status.Ongoing

#77 Add phone tests
  src/main/java/seedu/address/model/phone/Brand.java
  src/main/java/seedu/address/model/phone/Capacity.java
  src/main/java/seedu/address/model/phone/Colour.java
  src/main/java/seedu/address/model/phone/Cost.java
  src/main/java/seedu/address/model/phone/Name.java
  src/main/java/seedu/address/model/phone/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/java/seedu/address/model/phone/BrandTest.java
  src/test/java/seedu/address/model/phone/ColourTest.java
  src/test/java/seedu/address/model/phone/CostTest.java
  src/test/java/seedu/address/model/phone/NameTest.java
  src/test/java/seedu/address/model/phone/PhoneTest.java
  src/test/java/seedu/address/testutil/PhoneBuilder.java
  src/test/java/seedu/address/testutil/TypicalPhones.java
Labels: status.Ongoing

#79 Find commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/FindPhoneCommand.java
  src/main/java/seedu/address/model/order/IdContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/phone/PhoneNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: status.Ongoing

#81 Add customer order schedule tests
  src/main/java/seedu/address/model/customer/ContactNumber.java
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/model/customer/CustomerName.java
  src/main/java/seedu/address/model/customer/Email.java
  src/main/java/seedu/address/model/customer/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/phone/Brand.java
  src/main/java/seedu/address/model/phone/Colour.java
  src/main/java/seedu/address/model/phone/Cost.java
  src/main/java/seedu/address/model/phone/Phone.java
  src/main/java/seedu/address/model/phone/PhoneName.java
  src/main/java/seedu/address/model/phone/PhoneNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/Venue.java
  src/main/java/seedu/address/ui/cards/CustomerCard.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/java/seedu/address/ui/cards/PhoneCard.java
  src/main/java/seedu/address/ui/cards/ScheduleCard.java
  src/test/java/seedu/address/model/customer/ContactNumberTest.java
  src/test/java/seedu/address/model/customer/CustomerNameTest.java
  src/test/java/seedu/address/model/customer/CustomerTest.java
  src/test/java/seedu/address/model/customer/EmailTest.java
  src/test/java/seedu/address/model/customer/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/customer/UniqueCustomerListTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/PriceTest.java
  src/test/java/seedu/address/model/phone/NameTest.java
  src/test/java/seedu/address/model/phone/PhoneTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/model/schedule/VenueTest.java
  src/test/java/seedu/address/testutil/CustomerBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/PhoneBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: status.Ongoing

#101 Add additional tests for Phone model
  src/main/java/seedu/address/model/phone/Brand.java
  src/main/java/seedu/address/model/phone/Colour.java
  src/main/java/seedu/address/model/phone/Cost.java
  src/main/java/seedu/address/model/phone/Phone.java
  src/main/java/seedu/address/model/phone/PhoneName.java
  src/test/java/seedu/address/model/phone/PhoneNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/phone/PhoneTest.java
  src/test/java/seedu/address/model/phone/UniquePhoneListTest.java
  src/test/java/seedu/address/testutil/PhoneBuilder.java
Labels: priority.High, type.Task

#108 Help exit command
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCustomerCommand.java
  src/main/java/seedu/address/logic/commands/ListOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListPhoneCommand.java
  src/main/java/seedu/address/logic/commands/ListScheduleCommand.java
  src/main/java/seedu/address/logic/commands/UiChange.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/exception/EnumNotPresentException.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: priority.High, type.Task

#110 implement switching Tab panels command
  src/main/java/seedu/address/logic/commands/SwitchCustomerPanelCommand.java
  src/main/java/seedu/address/logic/commands/SwitchOrderPanelCommand.java
  src/main/java/seedu/address/logic/commands/SwitchPhonePanelCommand.java
  src/main/java/seedu/address/logic/commands/SwitchSchedulePanelCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SellerManagerParser.java
Labels: priority.High, type.Task

#113 Add Customer storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/CustomerBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedCustomer.java
  src/main/java/seedu/address/storage/JsonCustomerBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableCustomerBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/main.iml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/test.iml
Labels: priority.High, type.Task

#111 Fix models
  src/main/java/seedu/address/model/customer/ContactNumber.java
  src/main/java/seedu/address/model/customer/Customer.java
  src/main/java/seedu/address/model/customer/CustomerName.java
  src/main/java/seedu/address/model/customer/Email.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/Price.java
  src/main/java/seedu/address/model/order/Status.java
  src/main/java/seedu/address/model/phone/Brand.java
  src/main/java/seedu/address/model/phone/Colour.java
  src/main/java/seedu/address/model/phone/Cost.java
  src/main/java/seedu/address/model/phone/IdentityNumber.java
  src/main/java/seedu/address/model/phone/Phone.java
  src/main/java/seedu/address/model/phone/PhoneName.java
  src/main/java/seedu/address/model/phone/SerialNumber.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/model/schedule/Venue.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/ui/cards/ScheduleCard.java
  src/test/java/seedu/address/model/customer/ContactNumberTest.java
  src/test/java/seedu/address/model/customer/CustomerTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/phone/IdentityNumberTest.java
  src/test/java/seedu/address/model/phone/PhoneTest.java
  src/test/java/seedu/address/model/phone/SerialNumberTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/PhoneBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalPhones.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, severity.High, type.Bug

#116 Add money util
  src/main/java/seedu/address/commons/util/MoneyUtil.java
  src/test/java/seedu/address/commons/util/MoneyUtilTest.java
Labels: priority.High, type.Task

#102 Add commands and parsers for Phone class and edit sampleDataUtil
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/addcommand/AddCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddPhoneCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeletePhoneCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditPhoneCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/findcommand/FindPhoneCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListCustomerCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListOrderCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListPhoneCommand.java
  src/main/java/seedu/address/logic/commands/listcommand/ListScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SellerManagerParser.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddPhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeletePhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditPhoneCommandParser.java
  src/main/java/seedu/address/model/phone/Capacity.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, status.Ongoing, type.Task

#117 Implement cascade on delete/edit for model
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/order/UniqueOrderListTest.java
  src/test/java/seedu/address/model/schedule/UniqueScheduleListTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High, type.Task

#103 Adding GUI tests into SML
  build.gradle
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/AlertDialogHandle.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/guitests/guihandles/CustomerCardHandle.java
  src/test/java/guitests/guihandles/CustomerListPanelHandle.java
  src/test/java/guitests/guihandles/HelpWindowHandle.java
  src/test/java/guitests/guihandles/MainMenuHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/NodeHandle.java
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ResultDisplayHandle.java
  src/test/java/guitests/guihandles/StageHandle.java
  src/test/java/guitests/guihandles/StatusBarFooterHandle.java
  src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
  src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java
Labels: priority.High, status.Ongoing, type.Task

#115 Add Schedule commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/addcommand/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/deletecommandparser/DeleteScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/schedule/Schedule.java
  src/main/java/seedu/address/ui/cards/ScheduleCard.java
  src/main/resources/view/ScheduleListCard.fxml
Labels: priority.High, status.Ongoing

#118 Added phone storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAdaptedPhone.java
  src/main/java/seedu/address/storage/JsonCustomerBookStorage.java
  src/main/java/seedu/address/storage/JsonPhoneBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializablePhoneBook.java
  src/main/java/seedu/address/storage/PhoneBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#119 Add commands and parsers for Orders and add sample data for OrderBook
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CancelOrderCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CancelOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditOrderCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/resources/view/OrderListCard.fxml
Labels: priority.High

#106 Add tests for all the books and ModelManager
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/CustomerBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/OrderBookTest.java
  src/test/java/seedu/address/model/PhoneBookTest.java
  src/test/java/seedu/address/model/ScheduleBookTest.java
  src/test/java/seedu/address/testutil/CustomerBookBuilder.java
  src/test/java/seedu/address/testutil/OrderBookBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/PhoneBookBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBookBuilder.java
  src/test/java/seedu/address/testutil/ScheduleBuilder.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalPhones.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
Labels: priority.High

#121 Added Schedule storage.
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonScheduleBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableScheduleBook.java
  src/main/java/seedu/address/storage/ScheduleBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#105 Add calendar panel to show schedule
  build.gradle
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPanel.java
  src/main/java/seedu/address/ui/panels/CalendarPanel.java
  src/main/java/seedu/address/ui/panels/PhoneListPanel.java
  src/main/resources/view/CalendarPanel.fxml
  src/main/resources/view/TabPanel.fxml
Labels: priority.High, status.Ongoing

#83 Stats command + Stats test
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StatsParseUtil.java
  src/main/java/seedu/address/commons/util/StatsPayload.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/SwitchOrderPanelCommand.java
  src/main/java/seedu/address/logic/commands/statisticcommand/StatisticType.java
  src/main/java/seedu/address/logic/commands/statisticcommand/StatsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/statistic/Statistic.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/java/seedu/address/ui/exception/EnumNotPresentException.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsWindow.fxml
  src/test/java/seedu/address/commons/util/StatsPayloadBuilder.java
  src/test/java/seedu/address/commons/util/StatsPayloadTest.java
  src/test/java/seedu/address/commons/util/TypicalStatsPayload.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/statistic/StatisticsManagerTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
Labels: priority.High, status.Ongoing, type.Task

#122 Add basic autocomplete
  src/main/java/seedu/address/ui/AutoCompleteTextField.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandSuggestions.java
  src/main/resources/view/CommandBox.fxml
Labels: priority.High, type.Task

#125 Add Order storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonOrderBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableOrderBook.java
  src/main/java/seedu/address/storage/OrderBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.High, type.Task

#126 Integration Testing
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
Labels: priority.High, status.Ongoing, type.Task

#129 minor string adjustments
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddPhoneCommand.java
  src/main/java/seedu/address/logic/commands/statisticcommand/StatsCommand.java
Labels: type.Bug

#134 Fix CancelOrderCommand bug
  src/main/java/seedu/address/logic/commands/CancelOrderCommand.java
Labels: severity.Medium, type.Bug, type.Task

#133 Fix json adapted files
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAdaptedPhone.java
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
  src/main/java/seedu/address/storage/JsonOrderBookStorage.java
  src/main/java/seedu/address/storage/JsonScheduleBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableOrderBook.java
  src/main/java/seedu/address/storage/JsonSerializableScheduleBook.java
Labels: severity.High, type.Bug, type.Task

#141 Integrate chart into Stats
  src/main/java/seedu/address/commons/util/StatsPayload.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/statistic/DateUtil.java
  src/main/java/seedu/address/statistic/Statistic.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/SMLTheme.css
  src/main/resources/view/StatisticsWindow.fxml
Labels: priority.High, status.Ongoing, type.Task

#140 Update guide and fix minor bugs
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/StatisticsCalculationAcitvityDiagram.puml
  docs/diagrams/StatsCommandSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/StatsCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/statisticcommand/StatsCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StatsCommandParser.java
  src/main/java/seedu/address/statistic/DateUtil.java
  src/main/java/seedu/address/statistic/Statistic.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/statistic/StatsParseUtil.java
  src/main/java/seedu/address/statistic/StatsPayload.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/util/StatsPayloadBuilder.java
  src/test/java/seedu/address/commons/util/TypicalStatsPayload.java
Labels: priority.High, type.Task

#145 add archivedOrder stuff
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/UiChange.java
  src/main/java/seedu/address/logic/commands/switchcommand/SwitchArchivedOrderPanelCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TabPanel.java
  src/main/java/seedu/address/ui/cards/ArchivedOrderCard.java
  src/main/java/seedu/address/ui/panels/ArchivedOrderListPanel.java
  src/main/resources/images/archiveIcon.png
  src/main/resources/view/ArchivedOrderListPanel.fxml
  src/main/resources/view/TabPanel.fxml
  src/main/resources/view/archivedOrderListCard.fxml
Labels: priority.High, status.Ongoing, type.Task

#148 Implement Archives
  docs/DeveloperGuide.adoc
  docs/diagrams/FindCommandSequenceDiagram.puml
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CompleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditOrderCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/ArchivedOrderBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/cards/ArchivedOrderCard.java
  src/main/resources/view/ArchivedOrderListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/clearcommand/ClearCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/clearcommand/ClearPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeletePhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/findcommand/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/findcommand/FindPhoneCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommand/ListCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/listcommand/ListPhoneCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/customer/predicates/ContactNumberContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/customer/predicates/CustomerNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: priority.High, type.Task

#151 Added StorageClassDiagram
  docs/diagrams/StorageClassDiagram.puml
Labels: priority.High, status.Ongoing, type.Task

#153 removed dependency on sample data for stats
  src/main/java/seedu/address/statistic/StatisticManager.java
Labels: priority.High, type.Task

#150 Edit UG/DG + delete schedulecard/schedulelistpanel
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/ScheduleCommandSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ScheduleCommandSequenceDiagram.png
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/java/seedu/address/ui/cards/ScheduleCard.java
  src/main/java/seedu/address/ui/panels/ScheduleListPanel.java
Labels: priority.High, type.Task

#154 Update DG (Find Customer Command) and add CommandHistory
  docs/DeveloperGuide.adoc
  docs/diagrams/CustomerPredicateClassDiagram.puml
  docs/diagrams/FindCustomerCommandSequenceDiagram1.puml
  docs/diagrams/FindCustomerCommandSequenceDiagram2.puml
  docs/images/CustomerPredicateClassDiagram.png
  docs/images/FindCustomerCommandSequenceDiagram1.png
  docs/images/FindCustomerCommandSequenceDiagram2.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CancelOrderCommand.java
  src/main/java/seedu/address/logic/commands/CompleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#147 Clean up model class diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelClassDiagram.puml
  gradle/wrapper/gradle-wrapper.properties
Labels: priority.High, type.Story

#157 Updated storage component for DG
  docs/DeveloperGuide.adoc
  docs/images/StorageClassDiagram.png
Labels: priority.High, type.Task

#158 Fix calendar bug
  src/main/java/seedu/address/ui/panels/CalendarPanel.java
Labels: type.Bug

#139 Gui tests
  .travis.yml
  build.gradle
  docs/team/johndoe.adoc
  src/main/java/seedu/address/statistic/DateUtil.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/resources/view/OrderListCard.fxml
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/CustomerCardHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/TabPanelHandle.java
  src/test/java/guitests/guihandles/cards/CustomerCardHandle.java
  src/test/java/guitests/guihandles/cards/PhoneCardHandle.java
  src/test/java/guitests/guihandles/panels/CustomerListPanelHandle.java
  src/test/java/guitests/guihandles/panels/OrderListPanelHandle.java
  src/test/java/guitests/guihandles/panels/PhoneListPanelHandle.java
  src/test/java/seedu/address/commons/util/TypicalStatsPayload.java
  src/test/java/seedu/address/statistic/DateUtilTest.java
  src/test/java/seedu/address/statistic/StatisticsManagerTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
  src/test/java/seedu/address/ui/CustomerListPanelTest.java
  src/test/java/seedu/address/ui/GuiTestAssert.java
  src/test/java/seedu/address/ui/GuiTestAssertPhone.java
  src/test/java/seedu/address/ui/GuiUnitTest.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/MainWindowCloseTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
  src/test/java/seedu/address/ui/PhoneListPanelTest.java
  src/test/java/seedu/address/ui/ResultDisplayTest.java
  src/test/java/seedu/address/ui/StageExtension.java
  src/test/java/seedu/address/ui/UiPartExtension.java
Labels: priority.Medium, type.Task

#162 Add option for users to allow clashing schedules by including -allow in command + Tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/addcommand/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddScheduleCommand.java
  src/main/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddScheduleCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/java/seedu/address/ui/panels/CalendarPanel.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/addcommand/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/addcommand/AddScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/deletecommand/DeleteScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/addcommandparser/AddCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/addcommandparser/AddScheduleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deletecommandparser/DeleteScheduleCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/model/schedule/ScheduleTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalSchedules.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
Labels: priority.High, type.Task

#160 Tests
  src/main/java/seedu/address/statistic/StatsParseUtil.java
  src/test/java/seedu/address/commons/util/StatsPayloadTest.java
  src/test/java/seedu/address/logic/commands/statscommand/StatsCommandTest.java
  src/test/java/seedu/address/logic/commands/switchcommand/SwitchArchivedOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/switchcommand/SwitchCustomerPanelCommandTest.java
  src/test/java/seedu/address/logic/commands/switchcommand/SwitchOrderPanelCommandTest.java
  src/test/java/seedu/address/logic/commands/switchcommand/SwitchPhonePanelCommandTest.java
  src/test/java/seedu/address/logic/commands/switchcommand/SwitchSchedulePanelCommandTest.java
  src/test/java/seedu/address/model/phone/BrandContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/phone/CapacityContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/phone/ColourContainskeywordTest.java
  src/test/java/seedu/address/statistic/DateUtilTest.java
  src/test/java/seedu/address/statistic/StatisticsManagerTest.java
  src/test/java/seedu/address/statistic/StatsParseUtilTest.java
  src/test/java/seedu/address/statistic/StatsPayloadBuilder.java
  src/test/java/seedu/address/statistic/StatsPayloadTest.java
  src/test/java/seedu/address/statistic/TypicalStatsPayload.java
Labels: status.Ongoing, type.Task

#161 Implement Undo-Redo
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/UndoRedoStack.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/commands/UndoableCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/addcommand/AddPhoneCommand.java
  src/main/java/seedu/address/logic/commands/editcommand/EditPhoneCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/addcommandparser/AddPhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditPhoneCommandParser.java
  src/main/java/seedu/address/logic/parser/findcommandparser/FindPhoneCommandParser.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/addcommand/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/parser/addcommandparser/AddPhoneCommandParserTest.java
  src/test/java/seedu/address/model/customer/predicates/ContactNumberContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/customer/predicates/EmailContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/phone/CostTest.java
Labels: priority.High, type.Task

#167 Add command tests
  src/main/java/seedu/address/logic/commands/editcommand/EditScheduleCommand.java
  src/main/java/seedu/address/logic/parser/editcommandparser/EditScheduleCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/editcommand/EditScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/editcommand/EditScheduleDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/addcommandparser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/editcommandparser/EditScheduleCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/EditScheduleDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: type.Task

#169 fix order card
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/resources/view/OrderListCard.fxml
Labels: priority.High, type.Bug

#166 Fix JsonAdaptedSchedule month issue.
  src/main/java/seedu/address/storage/JsonAdaptedSchedule.java
Labels: priority.High, type.Bug

#163 Added Export to CSV feature
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: priority.High, status.Ongoing, type.Task

#171 Tests
  src/main/java/seedu/address/model/order/Status.java
  src/main/java/seedu/address/model/phone/Capacity.java
  src/main/java/seedu/address/statistic/DateUtil.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/resources/view/OrderListCard.fxml
  src/test/java/guitests/guihandles/cards/OrderCardHandle.java
  src/test/java/guitests/guihandles/panels/OrderListPanelHandle.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCustomerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedOrderTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPhoneTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalPhones.java
  src/test/java/seedu/address/ui/GuiTestAssert.java
  src/test/java/seedu/address/ui/HelpWindowTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
Labels: type.Bug, type.Task

#174 Tests
  docs/UserGuide.adoc
  src/main/java/seedu/address/ui/DefaultStatisticsWindow.java
Labels: type.Bug, type.Task

#175 added v2.0 things
  docs/UserGuide.adoc
Labels: type.Task

#176 Updated UG for export command
  docs/UserGuide.adoc
Labels: priority.High, type.Task

#178 moved image files
  docs/images/StatsExampleDefault.png
  docs/images/StatsExampleGraph.png
Labels: type.Bug

#180 add misc
  docs/UserGuide.adoc
Labels: type.Bug

#179 Implement AND Search and update UG
  docs/UserGuide.adoc
  docs/images/ug-command/ug-find-c-2.png
  docs/images/ug-command/ug-find-p-2.png
  docs/images/ug-command/ug-history.png
  docs/images/ug-command/ug-redo.png
  docs/images/ug-command/ug-undo.png
  src/main/java/seedu/address/model/customer/predicates/CustomerContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/phone/predicates/PhoneContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/findcommand/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/findcommand/FindOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/findcommand/FindPhoneCommandTest.java
  src/test/java/seedu/address/model/customer/predicates/CustomerContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/predicates/OrderContainsKeywordsPredicateTest.java
Labels: priority.High

#188 Tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/ug-command/ug-add-s.png
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/statistic/DateUtil.java
  src/main/java/seedu/address/statistic/StatisticManager.java
  src/main/java/seedu/address/ui/cards/ArchivedOrderCard.java
  src/main/resources/view/ArchivedOrderListCard.fxml
Labels: priority.High, type.Bug

#187 Add ClearScheduleCommand and test
  src/main/java/seedu/address/logic/commands/ScheduleCommand.java
  src/main/java/seedu/address/logic/commands/clearcommand/ClearScheduleCommand.java
  src/main/java/seedu/address/logic/parser/SellerManagerParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ScheduleCommandTest.java
  src/test/java/seedu/address/logic/commands/clearcommand/ClearScheduleCommandTest.java
  src/test/java/seedu/address/logic/parser/ScheduleCommandParserTest.java
Labels: type.Bug

#185 Fix ClearCommand(s) bug
  docs/UserGuide.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/clearcommand/ClearCustomerCommand.java
  src/main/java/seedu/address/logic/commands/clearcommand/ClearOrderCommand.java
  src/main/java/seedu/address/logic/commands/clearcommand/ClearPhoneCommand.java
  src/main/java/seedu/address/logic/commands/copycommand/CopyCustomerCommand.java
  src/main/java/seedu/address/logic/commands/copycommand/CopyOrderCommand.java
  src/main/java/seedu/address/logic/commands/copycommand/CopyPhoneCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/customer/ContactNumber.java
  src/test/java/seedu/address/logic/commands/clearcommand/ClearCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/clearcommand/ClearOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/clearcommand/ClearPhoneCommandTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
Labels: severity.High, type.Bug

#189 css changes, add labels
  src/main/resources/view/ArchivedOrderListCard.fxml
  src/main/resources/view/CustomerListCard.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/PhoneListCard.fxml
  src/main/resources/view/SMLTheme.css
Labels: type.Bug

#192 fix non showing of the schedule on archive order card
  src/main/java/seedu/address/ui/cards/ArchivedOrderCard.java
Labels: type.Bug

#193 Fix OrderBook Conflict Resolution Bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Bug
